module.exports = {
  "rules": {
    // "at-rule-blacklist": string|[],
    // "at-rule-empty-line-before": "always",
    "at-rule-name-case": "lower",
    "at-rule-name-newline-after": "always-multi-line",
    "at-rule-name-space-after": "always",
    "at-rule-no-unknown": true,
    "at-rule-no-vendor-prefix": true,
    // "at-rule-property-requirelist": {},
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": "never",
    // "at-rule-whitelist": string|[],
    // "block-closing-brace-empty-line-before": "always-multi-line",
    "block-closing-brace-newline-after": "always-multi-line",
    "block-closing-brace-newline-before": "always-multi-line",
    // "block-closing-brace-space-after": "-multi-line",
    "block-closing-brace-space-before": "never-single-line",
    "block-no-empty": true,
    "block-opening-brace-newline-after": "always-multi-line",
    // "block-opening-brace-newline-before": "always",
    // "block-opening-brace-space-after": "always",
    "block-opening-brace-space-before": "always",
    "color-hex-case": "lower",
    "color-hex-length": "short",
    "color-named": "always-where-possible",
    // "color-no-hex": true,
    "color-no-invalid-hex": true,
    // "comment-empty-line-before": "always",
    "comment-no-empty": true,
    "comment-whitespace-inside": "always",
    // "comment-word-blacklist": string|[],
    // "custom-media-pattern": string,
    "custom-property-empty-line-before": "always",
    // "custom-property-pattern": string,
    "declaration-bang-space-after": "always",
    "declaration-bang-space-before": "always",
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never",
    "declaration-block-single-line-max-declarations": 1,
    "declaration-block-trailing-semicolon": "always",
    // "declaration-colon-newline-after": "always",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-empty-line-before": "never",
    // "declaration-no-important": true,
    // "declaration-property-unit-blacklist": {},
    // "declaration-property-unit-whitelist": {},
    // "declaration-property-value-blacklist": {},
    // "declaration-property-value-whitelist": {},
    "font-family-name-quotes": "always-where-required",
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": true,
    "font-weight-notation": "numeric",
    // "function-blacklist": string|[],
    "function-calc-no-invalid": true,
    "function-calc-no-unspaced-operator": true,
    "function-comma-newline-after": "always-multi-line",
    "function-comma-newline-before": "never-multi-line",
    "function-comma-space-after": "always-single-line",
    "function-comma-space-before": "never",
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-max-empty-lines": 1,
    "function-name-case": "lower",
    "function-parentheses-newline-inside": "always-multi-line",
    "function-parentheses-space-inside": "never-single-line",
    "function-url-no-scheme-relative": true,
    "function-url-quotes": "always",
    // "function-url-scheme-blacklist": string|[],
    // "function-url-scheme-whitelist": string|[],
    // "function-whitelist": string|[],
    "function-whitespace-after": "always",
    "indentation": 2,
    "keyframe-declaration-no-important": true,
    // "keyframes-name-pattern": string,
    "length-zero-no-unit": true,
    "linebreaks": "unix",
    "max-empty-lines": 2,
    "max-line-length": 75,
    "max-nesting-depth": 2,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "always",
    // "media-feature-name-blacklist": string|[],
    "media-feature-name-case": "lower",
    "media-feature-name-no-unknown": true,
    "media-feature-name-no-vendor-prefix": true,
    // "media-feature-name-value-whitelist": {},
    // "media-feature-name-whitelist": string|[],
    "media-feature-parentheses-space-inside": "always",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always",
    "media-query-list-comma-newline-before": "always",
    "media-query-list-comma-space-after": "never",
    "media-query-list-comma-space-before": "never",
    "no-descending-specificity": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-empty-first-line": true,
    "no-eol-whitespace": true,
    "no-extra-semicolons": true,
    "no-invalid-double-slash-comments": true,
    "no-missing-end-of-source-newline": true,
    "no-unknown-animations": true,
    "number-leading-zero": "always",
    // "number-max-precision": int,
    "number-no-trailing-zeros": true,
    // "property-blacklist": string|[],
    "property-case": "lower",
    "property-no-unknown": true,
    // "property-no-vendor-prefix": true,
    // "property-whitelist": string|[],
    "rule-empty-line-before": "always-multi-line",
    "selector-attribute-brackets-space-inside": "always",
    // "selector-attribute-operator-blacklist": string|[],
    "selector-attribute-operator-space-after": "always",
    "selector-attribute-operator-space-before": "always",
    // "selector-attribute-operator-whitelist": string|[],
    "selector-attribute-quotes": "always",
    // "selector-class-pattern": string,
    // "selector-combinator-blacklist": string|[],
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    // "selector-combinator-whitelist": string|[],
    "selector-descendant-combinator-no-non-space": true,
    // "selector-id-pattern": string,
    "selector-list-comma-newline-after": "always",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "never",
    "selector-list-comma-space-before": "never",
    // "selector-max-attribute": int,
    // "selector-max-class": int,
    // "selector-max-combinators": int,
    // "selector-max-compound-selectors": int,
    // "selector-max-empty-lines": int,
    // "selector-max-id": int,
    // "selector-max-pseudo-class": int,
    // "selector-max-specificity": string,
    // "selector-max-type": int,
    // "selector-max-universal": int,
    // "selector-nested-pattern": string,
    "selector-no-qualifying-type": true,
    "selector-no-vendor-prefix": true,
    // "selector-pseudo-class-blacklist": string|[],
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-class-parentheses-space-inside": "always",
    // "selector-pseudo-class-whitelist": string|[],
    // "selector-pseudo-element-blacklist": string|[],
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-colon-notation": "single",
    "selector-pseudo-element-no-unknown": true,
    // "selector-pseudo-element-whitelist": string|[],
    "selector-type-case": "lower",
    "selector-type-no-unknown": true,
    "shorthand-property-no-redundant-values": true,
    "string-no-newline": true,
    "string-quotes": "single",
    // "time-min-milliseconds": int,
    // "unit-blacklist": string|[],
    "unit-case": "lower",
    "unit-no-unknown": true,
    // "unit-whitelist": string|[],
    "value-keyword-case": "lower",
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always",
    "value-list-comma-space-before": "always,
    // "value-list-max-empty-lines": int,
    // "value-no-vendor-prefix": true
  }
};
